// Discovers question banks and wires them into the app and service worker.
//
// Adding a state means adding one file, `public/banks/<id>.json`, and
// running the build. Nothing else is edited by hand:
//
//   - the `<id>` must match the filename and the file's own "id" field,
//     and the file must have "name", "title", and a "questions" array
//     (violations fail the build here, not silently in a browser),
//   - `src/Banks.elm` is regenerated (default bank id + known ids),
//   - the bank file list in `public/sw.js` between the BANKS markers
//     is regenerated so offline precaching covers the new bank.
//
// Runs automatically via the `prebuild` and `pretest` npm scripts.

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const banksDir = path.join(root, "public", "banks");

const ids = fs
  .readdirSync(banksDir)
  .filter((f) => f.endsWith(".json"))
  .map((f) => path.basename(f, ".json"))
  .sort();

if (ids.length === 0) {
  throw new Error("scripts/gen-banks: no bank files in public/banks/");
}

for (const id of ids) {
  const file = path.join(banksDir, id + ".json");
  const bank = JSON.parse(fs.readFileSync(file, "utf8"));
  if (bank.id !== id) {
    throw new Error(`scripts/gen-banks: ${file} has id "${bank.id}", expected "${id}"`);
  }
  for (const field of ["name", "title", "questions"]) {
    if (bank[field] === undefined) {
      throw new Error(`scripts/gen-banks: ${file} is missing "${field}"`);
    }
  }
  if (!Array.isArray(bank.questions) || bank.questions.length === 0) {
    throw new Error(`scripts/gen-banks: ${file} has no questions`);
  }
}

// Wyoming stays the default while it exists; otherwise alphabetical first.
const def = ids.includes("wy") ? "wy" : ids[0];

const elm =
  `module Banks exposing (default, ids)


{-| Generated by scripts/gen-banks.js — do not edit. Lists every bank file
found under public/banks/ at build time.
-}


default : String
default =
    "${def}"


ids : List String
ids =
    [ ${ids.map((id) => `"${id}"`).join("\n    , ")} ]
`;
fs.writeFileSync(path.join(root, "src", "Banks.elm"), elm);

const swPath = path.join(root, "public", "sw.js");
const sw = fs.readFileSync(swPath, "utf8");
const start = "// BANKS-START";
const end = "// BANKS-END";
const before = sw.slice(0, sw.indexOf(start) + start.length);
const after = sw.slice(sw.indexOf(end));
const entries = ids.map((id) => `  'banks/${id}.json',`).join("\n");
fs.writeFileSync(swPath, `${before}\n${entries}\n${after}`);

console.log(`scripts/gen-banks: ${ids.length} bank(s) [${ids.join(", ")}], default "${def}"`);
